version: '3.7'

services:
  base: &base
    tty: true
    stdin_open: true
    user: '1000'
    build:
      context: .
      target: development
    volumes:
      - ./:/app
    env_file: .env.example

  app:
    <<: *base
    hostname: app
    ports:
      - 3000:3000
      - 3001:3001
      - 3002:3002
      - 9229:9229

  test:
    <<: *base
    hostname: test
    ports:
      - 3000:3000