service: ton-challenge
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

functions:
  increment:
    handler: src/api/accessCounter/increment/app.handler
    events:
      - httpApi:
          path: /counter
          method: get
          request:
            parameters:
              querystrings:
                url: string

  get:
    handler: src/api/accessCounter/get/app.handler
    events:
      - httpApi:
          path: /counter/show
          method: get
          request:
            parameters:
              querystrings:
                url: string

  create:
    handler: src/api/register/user/create/app.handler
    events:
      - httpApi:
          path: /user/
          method: post

  getUser:
    handler: src/api/register/user/get/app.handler
    events:
      - httpApi:
          path: /user/show
          method: get
          request:
            parameters:
              querystrings:
                email: string
plugins:
  - serverless-offline