service: ton-challenge
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

functions:
  increment:
    handler: src/entrypoint/AccessCounter/counter.add
    events:
      - httpApi:
          path: /counter
          method: get
          request:
            parameters:
              querystrings:
                url: string
