service: ton-challenge
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

functions:
  hello:
    handler: src/entrypoint/handler.hello
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-offline

custom:
  serverless-offline:
    useDocker: true
